name: "Test"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  x86-64:
    runs-on: ubuntu-20.04
    steps:

    # Installation
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes

    # Build
    - name: Build
      run: |
        nix build -L

  # aarch64:
  #   runs-on: ubuntu-20.04
  #   steps:

  #   # Installation
  #   - uses: actions/checkout@v2.3.4
  #   - uses: cachix/install-nix-action@v12
  #     with:
  #       nix_path: nixpkgs=channel:nixos-unstable
  #   - name: Set up qemu
  #     uses: docker/setup-qemu-action@v1
  #   #- run: |
  #   #     DEBIAN_FRONTEND=noninteractive
  #   #     sudo bash -c "echo system-features = aarch64-linux arm-linux >> /etc/nix/nix.conf"

  #   # Build
  #   - name: Build
  #     run: |
  #       OPTIONS="--option system aarch64-linux
  #                --option sandbox false
  #                --extra-platforms aarch64-linux"
  #       nix-build $OPTIONS -E "with import <nixpkgs> {}; pkgs.python37Packages.callPackage ./default.nix { }"
  #       nix-build $OPTIONS -E "with import <nixpkgs> {}; pkgs.python38Packages.callPackage ./default.nix { }"
  #       nix-build $OPTIONS -E "with import <nixpkgs> {}; pkgs.python39Packages.callPackage ./default.nix { }"
