name: "Test"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  x86-64:
    runs-on: ubuntu-20.04
    steps:

    # Installation
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    # Build
    - name: Build
      run: |
        nix-build -E "with import <nixpkgs> {}; pkgs.python37Packages.callPackage ./default.nix { }"
        nix-build -E "with import <nixpkgs> {}; pkgs.python38Packages.callPackage ./default.nix { }"
        nix-build -E "with import <nixpkgs> {}; pkgs.python39Packages.callPackage ./default.nix { }"

  aarch64:
    runs-on: ubuntu-20.04
    steps:
    
    # Installation
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
          sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static

    # Build
    - name: Build
      run: |
        OPTIONS="--option system aarch64-linux
                 --option sandbox false
                 --extra-platforms aarch64-linux"
        nix-build $OPTIONS -E "with import <nixpkgs> {}; pkgs.python37Packages.callPackage ./default.nix { }"
        nix-build $OPTIONS -E "with import <nixpkgs> {}; pkgs.python38Packages.callPackage ./default.nix { }"
        nix-build $OPTIONS -E "with import <nixpkgs> {}; pkgs.python39Packages.callPackage ./default.nix { }"
